import Head from "next/head";
import styles from "../styles/Home.module.css";
import { getProps } from "../service/getProps";
import { Brand, Rubber, Shoes } from "@prisma/client";

interface Props {
  brands: Brand;
  rubbers: Rubber;
  shoes: Shoes;
}

const Home = (props: Props) => {
  console.log(props);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
      </main>
    </div>
  );
};

export default Home;

export const getServerSideProps = async () => await getProps.getAllData();
